export const type = {
  ADMIN_EDIT_USER_INFO_REQUEST: " ADMIN_EDIT_USER_INFO_REQUEST",
  ADMIN_EDIT_USER_INFO_SUCCESS: " ADMIN_EDIT_USER_INFO_SUCCESS",
  ADMIN_EDIT_USER_INFO_ERROR: " ADMIN_EDIT_USER_INFO_ERROR",
};
