export const type = {
  AUTH_USER_LOGIN_REQUEST: "AUTH_USER_LOGIN_REQUEST",
  AUTH_USER_LOGIN_SUCCESS: "AUTH_USER_LOGIN_SUCCESS",
  AUTH_USER_LOGIN_ERROR: "AUTH_USER_LOGIN_ERROR",

  AUTH_USER_REGISTER_REQUEST: "AUTH_USER_REGISTER_REQUEST",
  AUTH_USER_REGISTER_SUCCESS: "AUTH_USER_REGISTER_SUCCESS",
  AUTH_USER_REGISTER_ERROR: "AUTH_USER_REGISTER_ERROR",

  AUTH_USER_LOGOUT: "AUTH_USER_LOGIN",
};
