export const types = {
  INITIATE_ORDER: "INITIATE_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
  ORDER_SELECTED_PAYMENT: "ORDER_SELECTED_PAYMENT",
  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST ",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS ",
  CREATE_ORDER_ERROR: "CREATE_ORDER_ERROR ",

  // SOME TYPES
};
